const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

function quoteIdent(name) {
  return `"${String(name).replace(/"/g, '""')}"`;
}

function assertPgDumpAvailable() {
  const result = spawnSync('which', ['pg_dump'], { encoding: 'utf8' });
  return result.status === 0;
}

function createSqlDumpWithPgDump({ postgresUrl, outputPath }) {
  if (!assertPgDumpAvailable()) {
    throw new Error('pg_dump nao encontrado no PATH');
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const result = spawnSync(
    'pg_dump',
    [
      '--format=plain',
      '--no-owner',
      '--no-acl',
      '--clean',
      '--if-exists',
      `--file=${outputPath}`,
      `--dbname=${postgresUrl}`
    ],
    { encoding: 'utf8', env: process.env }
  );

  if (result.error) {
    throw new Error(`Falha ao executar pg_dump: ${result.error.message}`);
  }
  if (result.status !== 0) {
    const detail = (result.stderr || result.stdout || '').trim();
    const error = new Error(
      `pg_dump encerrou com codigo ${result.status}${detail ? `: ${detail}` : ''}`
    );
    error.pgDumpFailed = true;
    error.versionMismatch = /version mismatch/i.test(detail);
    throw error;
  }

  const stats = fs.statSync(outputPath);
  return { path: outputPath, sizeBytes: stats.size, method: 'pg_dump' };
}

function sqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'bigint') return String(value);
  if (value instanceof Date) return `'${value.toISOString().replace(/'/g, "''")}'`;
  if (Buffer.isBuffer(value)) return `'\\x${value.toString('hex')}'`;
  if (typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function listPublicTables(pool) {
  const { rows } = await pool.query(`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
    ORDER BY table_name
  `);
  return rows.map((row) => row.table_name);
}

async function getCreateTableDdl(pool, tableName) {
  const { rows: columns } = await pool.query(
    `
    SELECT
      a.attname AS column_name,
      pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
      a.attnotnull AS not_null,
      pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
      a.attidentity AS identity
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
    WHERE n.nspname = 'public'
      AND c.relname = $1
      AND a.attnum > 0
      AND NOT a.attisdropped
    ORDER BY a.attnum
  `,
    [tableName]
  );

  if (!columns.length) {
    throw new Error(`Tabela sem colunas: ${tableName}`);
  }

  const colDefs = columns.map((col) => {
    let def = `${quoteIdent(col.column_name)} ${col.data_type}`;
    if (col.identity === 'a') def += ' GENERATED ALWAYS AS IDENTITY';
    else if (col.identity === 'd') def += ' GENERATED BY DEFAULT AS IDENTITY';
    else if (col.column_default != null && col.identity === '') {
      def += ` DEFAULT ${col.column_default}`;
    }
    if (col.not_null && col.identity === '') def += ' NOT NULL';
    return def;
  });

  const { rows: pks } = await pool.query(
    `
    SELECT a.attname AS column_name
    FROM pg_index i
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY (i.indkey)
    WHERE n.nspname = 'public'
      AND c.relname = $1
      AND i.indisprimary
    ORDER BY array_position(i.indkey, a.attnum)
  `,
    [tableName]
  );

  if (pks.length) {
    colDefs.push(
      `PRIMARY KEY (${pks.map((row) => quoteIdent(row.column_name)).join(', ')})`
    );
  }

  return `CREATE TABLE ${quoteIdent(tableName)} (\n  ${colDefs.join(',\n  ')}\n);`;
}

async function getForeignKeys(pool) {
  const { rows } = await pool.query(`
    SELECT
      con.conname AS constraint_name,
      rel.relname AS table_name,
      pg_get_constraintdef(con.oid) AS definition
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND con.contype = 'f'
    ORDER BY rel.relname, con.conname
  `);
  return rows;
}

async function getIndexes(pool) {
  const { rows } = await pool.query(`
    SELECT
      c.relname AS table_name,
      i.relname AS index_name,
      pg_get_indexdef(ix.indexrelid) AS definition
    FROM pg_index ix
    JOIN pg_class c ON c.oid = ix.indrelid
    JOIN pg_class i ON i.oid = ix.indexrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND NOT ix.indisprimary
      AND NOT ix.indisexclusion
    ORDER BY c.relname, i.relname
  `);
  return rows;
}

async function createSqlDumpWithNode(pool, outputPath) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  const out = fs.createWriteStream(outputPath, { encoding: 'utf8' });

  const write = (line = '') =>
    new Promise((resolve, reject) => {
      out.write(`${line}\n`, (err) => (err ? reject(err) : resolve()));
    });

  await write('-- Terra Organica logical SQL backup (Node)');
  await write(`-- generated_at: ${new Date().toISOString()}`);
  await write('BEGIN;');
  await write('SET session_replication_role = replica;');
  await write('');

  const tables = await listPublicTables(pool);

  for (const table of [...tables].reverse()) {
    await write(`DROP TABLE IF EXISTS ${quoteIdent(table)} CASCADE;`);
  }
  await write('');

  for (const table of tables) {
    await write(await getCreateTableDdl(pool, table));
    await write('');
  }

  for (const index of await getIndexes(pool)) {
    await write(`${index.definition};`);
  }
  await write('');

  for (const table of tables) {
    const quoted = quoteIdent(table);
    const { rows } = await pool.query(`SELECT * FROM ${quoted}`);
    if (!rows.length) continue;

    const columns = Object.keys(rows[0]);
    const colList = columns.map(quoteIdent).join(', ');
    await write(`-- data: ${table} (${rows.length} rows)`);

    for (const row of rows) {
      const values = columns.map((col) => sqlLiteral(row[col])).join(', ');
      await write(`INSERT INTO ${quoted} (${colList}) VALUES (${values});`);
    }
    await write('');
  }

  for (const fk of await getForeignKeys(pool)) {
    await write(
      `ALTER TABLE ${quoteIdent(fk.table_name)} ADD CONSTRAINT ${quoteIdent(fk.constraint_name)} ${fk.definition};`
    );
  }

  await write('');
  await write('SET session_replication_role = DEFAULT;');
  await write('COMMIT;');

  await new Promise((resolve, reject) => {
    out.end((err) => (err ? reject(err) : resolve()));
  });

  const stats = fs.statSync(outputPath);
  return { path: outputPath, sizeBytes: stats.size, method: 'node' };
}

/**
 * Preferencia: pg_dump plain. Fallback: dump logico via Node (ex.: mismatch de versao).
 */
async function createSqlDump({ postgresUrl, outputPath, pool }) {
  try {
    return createSqlDumpWithPgDump({ postgresUrl, outputPath });
  } catch (error) {
    const canFallback = error.versionMismatch || !assertPgDumpAvailable();
    if (!canFallback || !pool) throw error;
    return createSqlDumpWithNode(pool, outputPath);
  }
}

module.exports = {
  assertPgDumpAvailable,
  createSqlDump,
  createSqlDumpWithNode,
  createSqlDumpWithPgDump
};
